server:
  port: 9000

spring:
  application:
    name: chronicle-sidecar

  cloud:
    gateway:
      routes:

        # ---------------- PRODUCT SERVICE ----------------
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/product/**

        # ---------------- CART SERVICE ----------------
        - id: cart_service
          uri: http://localhost:8082
          predicates:
            - Path=/cart/**

        # ---------------- PAYMENT SERVICE ----------------
        - id: payment_service
          uri: http://localhost:8083
          predicates:
            - Path=/payment/**

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
